### ISSUE TITLE
License for the dataset

### ISSUE THREAD

**Issue by jeswinoc** [sutdcv/Animal-Kingdom#2]
Hi,
I went through your paper. Really amazing work on the dataset and the action classification model. I noticed that there was no license in the repo or the website for the Animal kingdom dataset. Could you please add a license so that I can understand what is the scope of usage of the dataset and the model

**Comment by okiane** [comment]
Hi @jeswinoc, thank you for your interest in our dataset. :)

The videos are obtained from YouTube, and we do not hold copyrights to the videos. Hence, the Dataset should only be used for non-commercial scientific research purposes. 

If you are using it for the above intended purpose, you can download the Dataset via
https://forms.office.com/r/WCtC0FRWpA

If you have further questions, do contact me directly via email (second author in the email list in the main paper).

Thank you once again and wishing you a Happy New Year! :)
