### ISSUE TITLE
Question about dataset split

### ISSUE THREAD

**Issue by Solacex** [sutdcv/Animal-Kingdom#3]
With the JSON file for mmpose, it contains P1, P2, and P3_{5  species}. 
Does this mean 3 splits of the dataset? Why is the P3  saved according to the species?

**Comment by Solacex** [comment]
Well, it seems to correspond to the three protocols in the main paper?

**Comment by okiane** [comment]
Hi @Solacex, thank you for your interest in our dataset. :)

Yes, P1 refers to Protocol 1, P2 refers to Protocol 2, and likewise P3 refers to Protocol 3.

If you have further questions, do contact me directly via email (second author in the email list in the main paper).

Thank you once again and wishing you a Happy New Year! :)
