### ISSUE TITLE
Pose Estimation Protocol 2

### ISSUE THREAD

**Issue by HyoKong** [sutdcv/Animal-Kingdom#4]
Thank you so much for your contributions.

It seems that there are overlapping subclasses in train.json and test.json for pose estimation protocol 2.

I enumerate all the annotations in train.json and test.json.

There are 13 subclasses in the test.json:
![image](https://user-images.githubusercontent.com/32049327/225865122-c9a2a7ab-b843-4162-a6b8-a60f992c84a8.png)

and 49 sub_classes in the train.json:
![image](https://user-images.githubusercontent.com/32049327/225865351-f05106b5-3308-486b-934b-9ff3a192de9e.png)

There are overlapping subclasses in those two JSON files, for instance, 'Cat / Lion / Tiger / Cheetah / Leopard / Cheetah / Cougar / Civet cat'.

Could you please help to solve it?

Thank you so much!

**Comment by okiane** [comment]
Thank you @HyoKong for pointing this out. :) 
Closing this thread as we have resolved this a few months back via email.
